# Generated by Django 4.2 on 2023-06-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("netflixpage", "0002_genres_movies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="genres",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="netflixpage.genres"
            ),
        ),
    ]
