# Generated by Django 4.2 on 2023-06-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netflixpage", "0003_alter_movies_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="genres",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="movies",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
