# Generated by Django 4.2 on 2023-06-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netflixpage", "0004_alter_movies_genres_alter_movies_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="releasedate",
            field=models.CharField(max_length=300),
        ),
    ]
