# Generated by Django 4.2 on 2023-06-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netflixpage", "0005_alter_movies_releasedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="movieid",
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name="genres",
            name="genreid",
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
