# Generated by Django 4.2 on 2023-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netflixpage", "0006_movies_movieid_alter_genres_genreid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="liked_movies",
            field=models.ManyToManyField(
                related_name="likeduser", to="netflixpage.movies"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="watchlist_movies",
            field=models.ManyToManyField(
                related_name="watchlistuser", to="netflixpage.movies"
            ),
        ),
    ]
