# Generated by Django 4.2 on 2023-06-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netflixpage", "0007_user_liked_movies_user_watchlist_movies"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="embedurl",
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
