# Generated by Django 4.2 on 2023-07-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netflixpage", "0008_movies_embedurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genres",
            name="genreid",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movies",
            name="movieid",
            field=models.IntegerField(default=0),
        ),
    ]
