# Generated by Django 4.2 on 2023-07-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netflixpage", "0009_alter_genres_genreid_alter_movies_movieid"),
    ]

    operations = [
        migrations.AddField(
            model_name="genres",
            name="movie_data_retrieved",
            field=models.BooleanField(default=False),
        ),
    ]
