# Generated by Django 4.2 on 2023-07-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netflixpage", "0010_genres_movie_data_retrieved"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenresTVShows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genreid", models.IntegerField(default=0)),
                ("genre", models.CharField(max_length=100)),
                ("tvshow_data_retrieved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TVShows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tvshowid", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=300)),
                ("genres", models.CharField(max_length=300)),
                ("overview", models.TextField(max_length=300)),
                ("releasedate", models.CharField(max_length=300)),
                ("rating", models.FloatField(default=0)),
                ("posterpath", models.TextField(max_length=300)),
                ("embedurl", models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name="Genres",
            new_name="GenresMovies",
        ),
    ]
