# Generated by Django 4.2 on 2023-07-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netflixpage", "0011_genrestvshows_tvshows_rename_genres_genresmovies"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="liked_tvshows",
            field=models.ManyToManyField(
                related_name="likedusertvshow", to="netflixpage.tvshows"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="watchlist_tvshows",
            field=models.ManyToManyField(
                related_name="watchlistusertvshow", to="netflixpage.tvshows"
            ),
        ),
        migrations.AlterField(
            model_name="tvshows",
            name="embedurl",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="user",
            name="liked_movies",
            field=models.ManyToManyField(
                related_name="likedusermovie", to="netflixpage.movies"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="watchlist_movies",
            field=models.ManyToManyField(
                related_name="watchlistusermovie", to="netflixpage.movies"
            ),
        ),
    ]
